apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-svc
        image:  bajaks/webshop-api-microservices/authentication-service:v1.0
        imagePullPolicy:  Never
        ports:
        - containerPort: 8080
        env:
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: common-service-secret
                key:  jwt-key
          - name: SEED_IF_EMPTY
            valueFrom:
              configMapKeyRef:
                name: common-service-config
                key:  seed-empty
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: auth-db-secret
                key:  db-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-db-secret
                key:  db-password
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: auth-db-config
                key:  db-url
          - name: DB_DB
            valueFrom:
              configMapKeyRef:
                name: auth-db-config
                key:  db-type
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: auth-db-config
                key:  db-url
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: auth-db-config
                key:  db-port
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: auth-db-config
                key:  db-name
          - name: SSL_MODE
            valueFrom:
              configMapKeyRef:
                name: auth-db-config
                key:  db-ssl-mode



---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
    # clusterIP:  None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

